function [yawRateRef, vyRef] = referenceGen(deltaF,vx)
% Inputs: 
%    deltaF: Steering angle in radiants, 
%    vx: vehicle longitudinal velocity in m/s
% Outputs:
%    yawRateRef: yaw rate reference in rad/s
%    vyref: lateral velocity reference in m/s
global g m L l_f l_r C_f C_r mue 

% implement reference generator according to ESC notes
yawRateRef = ...
betaRef = ...
...
...
...
vyRef = ...
